<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>673fedee-9a6a-4c6a-b546-9d753d224e5a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    <PackageReference Include="Svix" Version="1.95.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Expade.Infrastructure\Expade.Infrastructure.csproj" />
    <ProjectReference Include="..\Expade.Core\Expade.Core.csproj" />
  </ItemGroup>

</Project>
